// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/filter.js', ['glif.filter'], ['glif.shader'], false);
goog.addDependency('../../../../src/glif.js', ['glif'], ['glif.filter', 'glif.shader'], false);
goog.addDependency('../../../../src/shader.js', ['glif.shader'], [], false);
